FROM mcr.microsoft.com/devcontainers/typescript-node:18

# Install global packages
RUN npm install -g http-server

# Set the working directory
WORKDIR /workspaces/session-recorder

# Expose port for web server
EXPOSE 3000
